<?php
$this->headTitle('Allergens');

$this->mainMenu()->setActiveItemId('dashboard');

$this->pageBreadcrumbs()->setItems([
            'Dashboard'=>$this->url('dashboard'),
            'Allergen'=>$this->url('allergen'),
            ]);
?>
<h1><?php echo $this->controller ?> Management</h1>
<div class="row">
<?php  if($this->activeUser['role'] === 'admin') { ?>
        <p>
            <a class="btn btn-primary" href="<?php echo $this->url('allergen/add', array()); ?>">NEW</a>
        </p>
<?php } ?>

        <table class="table table-striped table-bordered">
            <thead class="thead-inverse">
            <tr>
                <th>ACTIONS</th>
                <th>id</th>
                <th>name</th>
                <th>type</th>
                <th>regions</th>
                <th>season</th>
            </tr>
            </thead>
            <?php foreach ($this->objs as $obj) : ?>
                <tr id="row_<?php echo $obj->id ?>">
                    <td style="width: 400px; !important;">
                        <div class="row">
                            <div class="col-sm-4">
                                <a class="btn btn-primary" href="<?php echo $this->url('allergen/view',
                                    ['id' => $obj->id]); ?>">View</a>
                            </div>
                            <?php if($this->activeUser['role'] === 'admin' || $this->activeUser['role'] === 'practice') { ?>
                            <div class="col-sm-4">
                                <a class="btn btn-primary" href="<?php echo $this->url('allergen/edit',
                                    ['id' => $obj->id]); ?>">Edit</a>
                            </div>
                            <?php } ?>
                            <?php if($this->activeUser['role'] === 'admin' || $this->activeUser['role'] === 'practice') { ?>
                            <div class="col-sm-4">
                                <a class="btn btn-danger delete" href="<?php echo $this->url('allergen/delete',
                                    ['id' => $obj->id]); ?>">Delete</a>
                            </div>
                            <?php } ?>
                        </div>
                    </td>
                    <td><?php echo $this->escapeHtml($obj->id);?></td>
                    <td><?php echo $this->escapeHtml($obj->name);?></td>
                    <td><?php echo $this->escapeHtml($obj->type);?></td>
                    <td><?php echo $this->escapeHtml($obj->regions);?></td>
                    <td><?php echo $this->escapeHtml($obj->season);?></td>
                </tr>
            <?php endforeach; ?>
        </table>
</div>
<div class="row error">
    <?php echo $this->flashMessenger()->render(); ?>
</div>
<style>
    td { padding: 5px}
    .table th {
        border-left: 1px solid #ccc;
        white-space: nowrap;
    }
    .table td {
        border-bottom: 1px solid #ccc;
        white-space: nowrap;
        padding: 10px 5px;
    }
    .error {color: red; font-weight: bold}
</style>
<script>
$(".delete").click(function() {
    var choice = confirm('Are you sure you want to delete user');
    if(choice === true){
        return true
    }
    return false;
});
</script>


