<?php
$this->headTitle('Users');

$this->mainMenu()->setActiveItemId('dashboard');

$this->pageBreadcrumbs()->setItems([
            'Dashboard'=>$this->url('dashboard'),
            'Users'=>$this->url('user'),
            ]);
?>
<h1>User Management</h1>
<div class="row">
<?php  if($this->activeUser['role'] === 'admin') { ?>
        <p>
            <a class="btn btn-primary" href="<?php echo $this->url('user/add', array()); ?>">NEW</a>
        </p>
<?php } ?>

        <table class="table table-striped table-bordered">
            <thead class="thead-inverse">
            <tr>
                <th>-------------------ACTIONS-------------------</th>
                <th>id</th>
                <th>user</th>
                <th>email</th>
                <th>password</th>
                <th>name</th>
                <th>role</th>
                <th>practice</th>
                <th>region</th>
            </tr>
            </thead>
            <?php foreach ($this->users as $user) : ?>
                <tr id="row_<?php echo $user->id ?>">
                    <td style="width: 400px; !important;">
                        <div class="row">
                            <div class="col-sm-4">
                                <a class="btn btn-primary" href="<?php echo $this->url('user/view',
                                    ['id' => $user->id]); ?>">View</a>
                            </div>
                            <?php if($this->activeUser['role'] === 'admin' || $this->activeUser['role'] === 'practice') { ?>
                            <div class="col-sm-4">
                                <a class="btn btn-primary" href="<?php echo $this->url('user/edit',
                                    ['id' => $user->id]); ?>">Edit</a>
                            </div>
                            <?php } ?>
                            <?php if($this->activeUser['role'] === 'admin' || $this->activeUser['role'] === 'practice') { ?>
                            <div class="col-sm-4">
                                <a class="btn btn-danger delete" href="<?php echo $this->url('user/delete',
                                    ['id' => $user->id]); ?>">Delete</a>
                            </div>
                            <?php } ?>
                        </div>
                    </td>
                    <td><?php echo $this->escapeHtml($user->id);?></td>
                    <td><?php echo $this->escapeHtml($user->user);?></td>
                    <td class="user_email"><?php echo $this->escapeHtml($user->email);?></td>
                    <td><?php echo $this->escapeHtml($user->password);?></td>
                    <td><?php echo $this->escapeHtml($user->name);?></td>
                    <td><?php echo $this->escapeHtml($user->role);?></td>
                    <td><?php echo $this->escapeHtml($user->pid);?></td>
                    <td><?php echo $this->escapeHtml($user->region);?></td>
                </tr>
            <?php endforeach; ?>
        </table>
</div>
<div class="row error">
    <?php echo $this->flashMessenger()->render(); ?>
</div>
<style>
    td { padding: 5px}
    .table th {
        border-left: 1px solid #ccc;
        white-space: nowrap;
    }
    .table td {
        border-bottom: 1px solid #ccc;
        white-space: nowrap;
        padding: 10px 5px;
    }
    .error {color: red; font-weight: bold}
</style>
<script>
$(".delete").click(function() {
    var choice = confirm('Are you sure you want to delete user');
    if(choice === true){
        return true
    }
    return false;
});
</script>


