<?php
$this->headTitle('Learnings');

$this->mainMenu()->setActiveItemId('dashboard');

$this->pageBreadcrumbs()->setItems([
            'Dashboard'=>$this->url('dashboard'),
            'Learning Centers'=>$this->url('learning'),
            ]);
?>
<h1><?php echo $this->controller ?> Management</h1>
<div class="row">
<?php  if($this->activeUser['role'] === 'admin') { ?>
        <p>
            <a class="btn btn-primary" href="<?php echo $this->url('learning/add', array()); ?>">NEW</a>
        </p>
<?php } ?>

        <table class="table table-striped table-bordered">
            <thead class="thead-inverse">
            <tr>
                <th>---------------------ACTIONS----------------</th>
                <th>id</th>
                <th>name</th>
                <th>contact</th>
                <th>email</th>
                <th>address</th>
                <th>address2</th>
                <th>city</th>
                <th>state</th>
                <th>zip</th>
                <th>phone</th>
                <th>region</th>
            </tr>
            </thead>
            <?php foreach ($this->paginator as $obj) : ?>
                <tr id="row_<?php echo $obj->id ?>">
                    <td style="width: 400px; !important;">
                        <div class="row">
                            <div class="col-sm-4">
                                <a class="btn btn-primary" href="<?php echo $this->url('learning/view',
                                    ['id' => $obj->id]); ?>">View</a>
                            </div>
                            <?php if($this->activeUser['role'] === 'admin' || $this->activeUser['role'] === 'practice') { ?>
                            <div class="col-sm-4">
                                <a class="btn btn-primary" href="<?php echo $this->url('learning/edit',
                                    ['id' => $obj->id]); ?>">Edit</a>
                            </div>
                            <?php } ?>
                            <?php if($this->activeUser['role'] === 'admin' || $this->activeUser['role'] === 'practice') { ?>
                            <div class="col-sm-4">
                                <a class="btn btn-danger delete" href="<?php echo $this->url('learning/delete',
                                    ['id' => $obj->id]); ?>">Delete</a>
                            </div>
                            <?php } ?>
                        </div>
                    </td>
                    <td><?php echo $this->escapeHtml($obj->id);?></td>
                    <td><?php echo $this->escapeHtml($obj->name);?></td>
                    <td><?php echo $this->escapeHtml($obj->contact);?></td>
                    <td><?php echo $this->escapeHtml($obj->email);?></td>
                    <td><?php echo $this->escapeHtml($obj->address);?></td>
                    <td><?php echo $this->escapeHtml($obj->address2);?></td>
                    <td><?php echo $this->escapeHtml($obj->city);?></td>
                    <td><?php echo $this->escapeHtml($obj->state);?></td>
                    <td><?php echo $this->escapeHtml($obj->zip);?></td>
                    <td><?php echo $this->escapeHtml($obj->phone);?></td>
                    <td><?php echo $this->escapeHtml($obj->region);?></td>
                </tr>
            <?php endforeach; ?>
        </table>
</div>
<div class="row error">
    <?php echo $this->flashMessenger()->render(); ?>
</div>
<div class="row">
    <?= $this->paginationControl(
    // The paginator object:
        $this->paginator,
        // The scrolling style:
        'sliding',
        // The partial to use to render the control:
        'partials/paginator',
        // The route to link to when a user clicks a control link:
        ['route' => 'learning']
    ) ?>
</div>
<style>
    td { padding: 5px}
    .table th {
        border-left: 1px solid #ccc;
        white-space: nowrap;
    }
    .table td {
        border-bottom: 1px solid #ccc;
        white-space: nowrap;
        padding: 10px 5px;
    }
    .error {color: red; font-weight: bold}
</style>
<script>
$(".delete").click(function() {
    var choice = confirm('Are you sure you want to delete user');
    if(choice === true){
        return true
    }
    return false;
});
</script>


